### ISSUE TITLE
使用方法？

### ISSUE THREAD

**Issue by Z-fly** [Werewolf-Wu/BaoziManga_Spider#1]

**Comment by Werewolf-Wu** [comment]
1. 直接访问，获得你的Cookies ＆ Headers，填入cookies_and_headers中
2. 本地搭个flaresolverr(并不麻烦，github上能搜到这个，win下有现成二进制文件，运行即可)
3. 修改main，在里面创建一个漫画类，传入你想看的漫画的首页（有各种列表）的链接，然后依次调用那三个方法
4. 完成了

依赖httpx和grequests，没有写进说明（那时候还没学写协程，所以才用grequests解决的）

这个是我去年打发时间写的东西，因为我网络的问题导致无法解决cloudflare的验证才导致了不小的麻烦，而且近期没有需求，所以没有维护....可能你重写一个也比看懂我写的大粪更加简单吧(x

顺带，不推荐爬包子漫画，我爬蓝溪镇写的，结果发现好几章就直接没有

**Comment by Z-fly** [comment]
https://github.com/journey3510/10Comic
那还是用这个吧，直接图形界面都有了

**Comment by Werewolf-Wu** [comment]
没毛病的
